http.port: 8000
chainid: 7092415936
log.level: 2
datadir: /Users/jesseakoh/Desktop/work/code/openrelay/cardinal-evm/hardfork-tests/fd5-data
reorg.threshold: 128
cloudwatch:
  namespace: cardinal
  dimensions:
    network: fd5
#topic.transactions: hoodi-tx
block.wait.ms: 2000
brokers:
  - url: "null://"